import {
    FaFacebookF,
    FaInstagram,
    FaTiktok,
    FaTwitter,
    FaYoutube,
    FaLinkedinIn,
    FaSnapchatGhost,
    FaPinterestP,
    FaWhatsapp,
    FaTelegramPlane,
    FaRedditAlien,
    FaDiscord,
} from "react-icons/fa";

export const socialLogos = [
    {
        id: 1,
        name: "Facebook",
        icon: FaFacebookF,
        color: "from-blue-600 to-blue-400",
        size: "large",
        top: "5%",
        left: "3%",
        anim: "float-slow",
        delay: "0s",
    },
    {
        id: 2,
        name: "Instagram",
        icon: FaInstagram,
        color: "from-pink-600 to-purple-600",
        size: "large",
        top: "15%",
        right: "5%",
        anim: "float",
        delay: "1s",
    },
    {
        id: 3,
        name: "TikTok",
        icon: FaTiktok,
        color: "from-black to-gray-700",
        size: "large",
        bottom: "10%",
        left: "7%",
        anim: "float-slow",
        delay: "2s",
    },
    {
        id: 4,
        name: "Twitter",
        icon: FaTwitter,
        color: "from-blue-400 to-blue-300",
        size: "medium",
        top: "30%",
        right: "10%",
        anim: "float-fast",
        delay: "0.5s",
    },
    {
        id: 5,
        name: "YouTube",
        icon: FaYoutube,
        color: "from-red-600 to-red-500",
        size: "medium",
        bottom: "25%",
        right: "15%",
        anim: "float",
        delay: "3s",
    },
    {
        id: 6,
        name: "LinkedIn",
        icon: FaLinkedinIn,
        color: "from-blue-700 to-blue-600",
        size: "medium",
        top: "60%",
        left: "10%",
        anim: "float-fast",
        delay: "1.5s",
    },
    {
        id: 7,
        name: "Snapchat",
        icon: FaSnapchatGhost,
        color: "from-yellow-400 to-yellow-300",
        size: "small",
        top: "45%",
        right: "3%",
        anim: "float-fast",
        delay: "2.5s",
    },
    {
        id: 8,
        name: "Pinterest",
        icon: FaPinterestP,
        color: "from-red-700 to-red-600",
        size: "small",
        bottom: "40%",
        left: "15%",
        anim: "float",
        delay: "4s",
    },
    {
        id: 9,
        name: "WhatsApp",
        icon: FaWhatsapp,
        color: "from-green-500 to-green-400",
        size: "small",
        top: "75%",
        right: "8%",
        anim: "float-slow",
        delay: "3.5s",
    },
    {
        id: 10,
        name: "Telegram",
        icon: FaTelegramPlane,
        color: "from-blue-500 to-blue-400",
        size: "small",
        bottom: "5%",
        right: "20%",
        anim: "float-fast",
        delay: "5s",
    },
    {
        id: 11,
        name: "Reddit",
        icon: FaRedditAlien,
        color: "from-orange-600 to-orange-500",
        size: "medium",
        top: "85%",
        left: "5%",
        anim: "float",
        delay: "2s",
    },
    {
        id: 12,
        name: "Discord",
        icon: FaDiscord,
        color: "from-purple-600 to-indigo-600",
        size: "small",
        top: "20%",
        left: "20%",
        anim: "float-fast",
        delay: "0.8s",
    },
];
